language: python
python:
  - "2.7"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda2/bin:$PATH
  - conda update -y conda
  - conda install -y pip
install:
  - pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
  - pip install --no-deps git+git://github.com/fchollet/keras.git
  - mkdir ~/.keras
  - "echo '{\"epsilon\": 1e-07, \"floatx\": \"float32\", \"backend\": \"tensorflow\"}' > ~/.keras/keras.json"
  - conda install -y --file requirements.txt
script: nosetests
